/*
 * Copyright 2011 Memetix, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.memetix.chits4jexamples;

import com.memetix.chits4j.agent.Agent;
import com.memetix.chits4j.agent.AgentService;
import com.memetix.chits4j.chit.Chit;
import com.memetix.chits4j.metric.Metric;
import com.memetix.chits4j.metric.MetricService;
import javax.swing.JOptionPane;

/**
 * A Swing client for testing the Chits API
 *
 * @author Jonathan Griggs <jonathan.griggs @ gmail.com>
 * @date Aug 7, 2011
 */
public class Chit4jGraphicalClient extends javax.swing.JFrame {
    AgentService aService = new AgentService();
    MetricService mService = new MetricService();

    /** Creates new form Chit4jGraphicalClient */
    public Chit4jGraphicalClient() {
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        metricName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        metricValue = new javax.swing.JTextField();
        writeMetricButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        statusText = new javax.swing.JTextArea();
        jToolBar2 = new javax.swing.JToolBar();
        jLabel3 = new javax.swing.JLabel();
        agentName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        chitList = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jLabel1.setText("Name");
        jToolBar1.add(jLabel1);

        metricName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metricNameActionPerformed(evt);
            }
        });
        jToolBar1.add(metricName);

        jLabel2.setText("Value");
        jToolBar1.add(jLabel2);
        jToolBar1.add(metricValue);

        writeMetricButton.setText("Write Metric");
        writeMetricButton.setFocusable(false);
        writeMetricButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        writeMetricButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        writeMetricButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                writeMetricAction(evt);
            }
        });
        jToolBar1.add(writeMetricButton);

        statusText.setColumns(20);
        statusText.setRows(5);
        jScrollPane1.setViewportView(statusText);

        jToolBar2.setRollover(true);

        jLabel3.setText("Agent");
        jToolBar2.add(jLabel3);
        jToolBar2.add(agentName);

        jButton1.setText("Refresh Agent");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshAgentPerform(evt);
            }
        });
        jToolBar2.add(jButton1);

        chitList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(chitList);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jToolBar2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
            .add(jToolBar1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jToolBar2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 322, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jToolBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void metricNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metricNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_metricNameActionPerformed

    private void writeMetricAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_writeMetricAction
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                writeMetric();
            }
        });
    }//GEN-LAST:event_writeMetricAction

    private void refreshAgentPerform(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshAgentPerform
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                refreshAgent();
            }
        });
    }//GEN-LAST:event_refreshAgentPerform

    private void writeMetric() {
        try {
            final Metric metric = new Metric();
            metric.setAgent(agentName.getText());
            metric.setName(metricName.getText());
            metric.setValue(metricValue.getText());
        
            statusText.append(mService.writeMetric(metric).encodeAsJSON().toString() + "\n");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Performing Localization : " + ex.toString(),"Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void refreshAgent() {
        try {
            final Agent agent = aService.getAgent(agentName.getText());
            for(Chit chit : agent.getChits()) {
                statusText.append(chit.getName() + "\n");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Performing Localization : " + ex.toString(),"Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Chit4jGraphicalClient().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField agentName;
    private javax.swing.JList chitList;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JTextField metricName;
    private javax.swing.JTextField metricValue;
    private javax.swing.JTextArea statusText;
    private javax.swing.JButton writeMetricButton;
    // End of variables declaration//GEN-END:variables
}
